
// Existing types... (ClinicalTestType, Branch, etc.)
export enum ClinicalTestType {
  BEP_ADAPTATION = 'BEP/IEP Dinamik Adaptasyon',
  DMP_STRESS = 'DMP Stres Simülatörü',
  CONFLICT_MANAGEMENT = 'Multidisipliner Çatışma',
  DATA_LITERACY = 'Klinik Veri Okuryazarlığı',
  BOUNDARY_INTEGRITY = 'Veli-Öğretmen Sınır İhlali',
  COGNITIVE_FLEXIBILITY = 'Metot Değişimi ve Esneklik',
  DE_ESCALATION_REFLEX = 'Kriz ve Güvenlik Yönetimi',
  PARENT_MANIPULATION = 'Veli Sınır Testi'
}

export enum Branch {
  OzelEgitim = 'Özel Eğitim',
  DilKonusma = 'Dil ve Konuşma Terapisi',
  Ergoterapi = 'Ergoterapi',
  Fizyoterapi = 'Fizyoterapi',
  Psikoloji = 'Psikoloji',
  PDR = 'PDR',
  CocukGelimi = 'Çocuk Gelişimi',
  OkulOncesi = 'Okul Öncesi',
  SinifOgretmenligi = 'Sınıf Öğretmenliği'
}

// --- ARMS (AKADEMİK REZONANS & MENTORLUK SİSTEMİ) TYPES ---

export interface StaffAssessment {
  id: string;
  staffId: string;
  timestamp: number;
  category: 'clinical' | 'parent_relations' | 'peer_collaboration' | 'ethics' | 'academic_growth';
  scores: {
    technical: number;
    soft_skills: number;
    institutional_fit: number;
  };
  rawFeedback: string;
  aiGapAnalysis: string;
}

export interface TrainingSlide {
  title: string;
  content: string;
  keyPoints: string[];
  clinicalCase?: string;
  discussionQuestion: string;
}

export interface IDP {
  id: string;
  staffId: string;
  createdAt: number;
  focusArea: string;
  identifiedGaps: string[];
  roadmap: {
    shortTerm: string;
    midTerm: string;
    longTerm: string;
  };
  recommendedTrainings: string[];
  autoGeneratedPresentation?: TrainingSlide[];
}

export interface StaffMember {
  id: string;
  name: string;
  branch: Branch;
  startDate: number;
  role: 'teacher' | 'coordinator' | 'senior';
  assessments: StaffAssessment[];
  currentIDP?: IDP;
  status: 'active' | 'on_leave' | 'probation';
}

// ... existing candidate types ...
export type ArchiveCategory = 'TALENT_POOL' | 'DISQUALIFIED' | 'FUTURE_REFERENCE' | 'HIRED_CONTRACTED' | 'BLACK_LIST';
export type Gender = 'Kadın' | 'Erkek' | 'Belirtilmemiş';
export type MaritalStatus = 'Bekar' | 'Evli' | 'Diğer';
export interface FormStep { id: string; title: string; description: string; }
export interface Question { id: string; category: string; text: string; type: 'radio' | 'text' | 'checkbox'; options?: string[]; weightedOptions?: Array<{ label: string; weights: Record<string, number | string>; analysisInsight: string; }>; requiredBranch?: string[]; }
export interface Certification { id: string; label: string; description: string; category: string; verificationQuestions: Question[]; }
export interface SimulationResult { scenario: string; parentPersona: string; candidateResponse: string; stressLevel: number; aiEvaluation: { ethicalBoundaryScore: number; empathyCalibration: number; professionalDistance: number; crisisResolutionEfficiency: number; clinicalTruths: string[]; criticalMistakes: string[]; neuralDivergence: { contradictionIndex: number; decisionPath: string; alternativeOutcome: string; dominantEmotion: string; }; microBehaviors: { toneAnalysis: string; nonVerbalPrediction: string; silenceTolerance: string; }; }; }
export interface IntelligenceSegment { score: number; status: 'optimal' | 'warning' | 'critical'; reasoning: string; behavioralIndicators: string[]; institutionalImpact: string; pros: string[]; cons: string[]; risks: string[]; }
export interface AIReport { score: number; integrityIndex: number; socialMaskingScore: number; summary: string; detailedAnalysisNarrative: string; recommendation: string; deepAnalysis: Record<string, IntelligenceSegment>; predictiveMetrics: { retentionProbability: number; burnoutRisk: number; learningVelocity: number; leadershipPotential: number; evolutionPath: string; }; interviewGuidance: { strategicQuestions: string[]; criticalObservations: string[]; simulationTasks: string[]; }; swot: { strengths: string[]; weaknesses: string[]; opportunities: string[]; threats: string[]; }; }
export interface AlgorithmicReport { overallScore: number; reliabilityIndex: number; ethicsScore: number; experienceWeight: number; retentionScore: number; burnoutResistance: number; fitScore: number; riskFlags: string[]; }
export interface Candidate { id: string; name: string; email: string; phone: string; age: number; gender: Gender; maritalStatus: MaritalStatus; branch: string; university: string; department: string; experienceYears: number; previousInstitutions: string; allTrainings: string[]; answers: Record<string, string | string[]>; timestamp: number; status: 'pending' | 'interview_scheduled' | 'rejected' | 'hired' | 'withdrawn' | 'archived'; archiveCategory?: ArchiveCategory; archiveNote?: string; adminNotes?: string; reminderNote?: string; report?: AIReport; algoReport?: AlgorithmicReport; interviewSchedule?: { date: string; time: string; method: string; location: string; }; cvData?: { base64: string; mimeType: string; fileName: string; }; }
export interface GlobalConfig { institutionName: string; primaryColor: string; accentColor: string; aiTone: 'strict' | 'balanced' | 'empathetic'; aiWeights: { ethics: number; clinical: number; experience: number; fit: number; }; aiPersona: { skepticism: number; empathy: number; formality: number; }; automation: { autoEmailOnSchedule: boolean; requireCvUpload: boolean; allowMultipleApplications: boolean; }; interviewSettings: { defaultDuration: number; bufferTime: number; autoStatusAfterInterview: boolean; defaultMeetingLink: string; }; notificationEmail: string; lastUpdated: number; }
