
import React, { useState, useEffect, useMemo } from 'react';
import { armsService } from '../../services/ai/armsService';
import { AreaChart, Area, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer } from 'recharts';
import PptxGenJS from 'pptxgenjs';

const StaffProfileView: React.FC<{ staffId: string }> = ({ staffId }) => {
  const [data, setData] = useState<any>(null);
  const [isLoading, setIsLoading] = useState(true);
  const [isAiProcessing, setIsAiProcessing] = useState(false);
  const [activeSlide, setActiveSlide] = useState(0);
  const [isFullscreen, setIsFullscreen] = useState(false);

  const fetchData = async () => {
    setIsLoading(true);
    try {
      const res = await fetch(`/api/staff?action=get_details&staffId=${staffId}`);
      const json = await res.json();
      setData(json);
    } catch (e) {
      console.error("Detail fetch error:", e);
    } finally {
      setIsLoading(false);
    }
  };

  useEffect(() => {
    fetchData();
  }, [staffId]);

  useEffect(() => {
    const handleKeyDown = (e: KeyboardEvent) => {
      if (!isFullscreen || !data?.activeIDP?.data?.autoGeneratedPresentation) return;
      const slides = data.activeIDP.data.autoGeneratedPresentation;
      
      if (e.key === 'ArrowRight' || e.key === 'Space') {
        setActiveSlide(s => Math.min(slides.length - 1, s + 1));
      } else if (e.key === 'ArrowLeft') {
        setActiveSlide(s => Math.max(0, s - 1));
      } else if (e.key === 'Escape') {
        setIsFullscreen(false);
      }
    };
    window.addEventListener('keydown', handleKeyDown);
    return () => window.removeEventListener('keydown', handleKeyDown);
  }, [isFullscreen, data]);

  const handleGenerateIDP = async () => {
    setIsAiProcessing(true);
    try {
      const newIdp = await armsService.generateIDP({
        profile: data.profile,
        assessments: data.assessments
      } as any);
      
      await fetch('/api/staff?action=save_idp', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ staffId, data: newIdp })
      });

      // @fix Line 62: generateTrainingSlides is now defined in armsService.ts to resolve the property access error.
      const slides = await armsService.generateTrainingSlides(newIdp, data.profile.branch);
      newIdp.autoGeneratedPresentation = slides;

      setData({ ...data, activeIDP: { data: newIdp } });
      alert("Nöral Gelişim Planı mühürlendi.");
    } catch (e) {
      alert("AI Analiz Motoru Hatası.");
    } finally {
      setIsAiProcessing(false);
    }
  };

  const handleExportPPTX = () => {
    const slides = data?.activeIDP?.data?.autoGeneratedPresentation;
    if (!slides || slides.length === 0) return;

    const pptx = new PptxGenJS();
    pptx.layout = 'LAYOUT_16x9';

    slides.forEach((slide: any) => {
      const s = pptx.addSlide();
      s.background = { color: '0F172A' };
      s.addText(slide.title, { x: 0.5, y: 0.5, w: '90%', h: 1, fontSize: 32, bold: true, color: 'EA580C' });
      if (slide.subtitle) s.addText(slide.subtitle, { x: 0.5, y: 1.2, w: '90%', h: 0.5, fontSize: 18, color: '94A3B8', italic: true });
      const bulletPoints = (slide.content || []).map((p: string) => ({ text: p, options: { bullet: true, color: 'FFFFFF', fontSize: 14 } }));
      s.addText(bulletPoints, { x: 0.5, y: 2.2, w: '60%', h: 3, valign: 'top' });
      s.addNotes(slide.speakerNotes || "");
    });

    pptx.writeFile({ fileName: `${data.profile.name.replace(/\s+/g, '_')}_Gelisim_Sunumu.pptx` });
  };

  const chartData = useMemo(() => {
    if (!data?.assessments) return [];
    return data.assessments.map((a: any) => ({
      date: new Date(a.timestamp).toLocaleDateString('tr-TR', { day: '2-digit', month: 'short' }),
      score: a.score
    }));
  }, [data]);

  if (isLoading) return <div className="py-20 text-center animate-pulse uppercase font-black text-slate-300 tracking-[0.3em] text-[10px]">Veri Rezonansı Kuruluyor...</div>;

  const idp = data.activeIDP?.data;

  return (
    <div className="space-y-6 animate-scale-in">
      {isFullscreen && idp?.autoGeneratedPresentation && (
        <div className="fixed inset-0 z-[1000] bg-slate-950 flex flex-col animate-fade-in outline-none" tabIndex={0}>
           <SlideContent 
             slide={idp.autoGeneratedPresentation[activeSlide]} 
             index={activeSlide} 
             total={idp.autoGeneratedPresentation.length} 
             full={true} 
             onClose={() => setIsFullscreen(false)} 
             onPrev={() => setActiveSlide(s => Math.max(0, s - 1))}
             onNext={() => setActiveSlide(s => Math.min(idp.autoGeneratedPresentation.length - 1, s + 1))}
           />
        </div>
      )}

      {/* TOP HEADER: ACADEMIC CREDENTIALS (DENSE) */}
      <div className="bg-white p-6 rounded-[2rem] border border-slate-200 shadow-sm relative overflow-hidden group">
         <div className="flex flex-col xl:flex-row justify-between items-center gap-6 relative z-10">
            <div className="flex items-center gap-5">
               <div className="w-16 h-16 bg-slate-950 rounded-2xl flex items-center justify-center text-white text-2xl font-black shadow-lg">
                  {data.profile.name.charAt(0)}
               </div>
               <div>
                  <h3 className="text-2xl font-black text-slate-900 tracking-tighter uppercase italic leading-none">{data.profile.name}</h3>
                  <div className="flex items-center gap-3 mt-2">
                     <span className="px-3 py-1 bg-orange-600 rounded-lg text-[9px] font-black text-white uppercase tracking-widest">{data.profile.branch}</span>
                     <span className="text-[9px] font-bold text-slate-400 uppercase tracking-widest">{data.profile.experience_years} YIL DENEYİM // {data.profile.university}</span>
                  </div>
               </div>
            </div>
            <div className="flex gap-3">
               <button 
                 onClick={handleGenerateIDP} 
                 disabled={isAiProcessing}
                 className="px-6 py-3 bg-slate-950 text-white rounded-xl text-[9px] font-black uppercase tracking-[0.1em] hover:bg-orange-600 transition-all shadow-md active:scale-95 disabled:opacity-50"
               >
                  {isAiProcessing ? 'ANALİZ...' : (idp ? 'GELİŞİMİ YENİLE' : 'PLANI BAŞLAT')}
               </button>
               {idp?.autoGeneratedPresentation && (
                 <div className="flex bg-slate-100 p-1 rounded-xl">
                    <button onClick={() => { setActiveSlide(0); setIsFullscreen(true); }} className="px-4 py-2 bg-white text-slate-900 rounded-lg text-[9px] font-black uppercase tracking-widest shadow-sm hover:bg-orange-600 hover:text-white transition-all">SUNUM</button>
                    <button onClick={handleExportPPTX} className="px-3 py-2 text-slate-400 hover:text-orange-600 transition-all">
                       <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2.5}><path d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4" /></svg>
                    </button>
                 </div>
               )}
            </div>
         </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-12 gap-6">
         <div className="lg:col-span-8 bg-white p-6 rounded-[2rem] border border-slate-200 shadow-sm h-[300px]">
            <h4 className="text-[10px] font-black text-slate-900 uppercase tracking-[0.2em] mb-4 border-l-4 border-orange-600 pl-3">Klinik Gelişim Eğrisi</h4>
            <div className="h-[220px]">
               <ResponsiveContainer width="100%" height="100%">
                  <AreaChart data={chartData}>
                     <defs>
                        <linearGradient id="colorScore" x1="0" y1="0" x2="0" y2="1">
                           <stop offset="5%" stopColor="#ea580c" stopOpacity={0.1}/>
                           <stop offset="95%" stopColor="#ea580c" stopOpacity={0}/>
                        </linearGradient>
                     </defs>
                     <CartesianGrid strokeDasharray="3 3" vertical={false} stroke="#f1f5f9" />
                     <XAxis dataKey="date" axisLine={false} tickLine={false} tick={{fontSize: 9, fontWeight: 700, fill: '#94a3b8'}} />
                     <YAxis axisLine={false} tickLine={false} tick={{fontSize: 9, fontWeight: 700, fill: '#94a3b8'}} domain={[0, 100]} />
                     <Tooltip contentStyle={{borderRadius: '12px', border: 'none', boxShadow: '0 10px 20px rgba(0,0,0,0.1)', fontSize: '10px'}} />
                     <Area type="monotone" dataKey="score" stroke="#ea580c" strokeWidth={3} fillOpacity={1} fill="url(#colorScore)" />
                  </AreaChart>
               </ResponsiveContainer>
            </div>
         </div>

         <div className="lg:col-span-4 bg-slate-900 p-6 rounded-[2rem] text-white shadow-lg flex flex-col h-[300px]">
            <h4 className="text-[10px] font-black text-orange-500 uppercase tracking-[0.2em] mb-4 border-b border-white/10 pb-2">Aktif Yetkinlikler</h4>
            <div className="flex-1 space-y-2 overflow-y-auto custom-scrollbar pr-1">
               {(data.profile.all_trainings || []).map((t: string, i: number) => (
                  <div key={i} className="px-3 py-2 bg-white/5 rounded-lg border border-white/5 flex items-center gap-3">
                     <div className="w-1.5 h-1.5 rounded-full bg-emerald-500"></div>
                     <span className="text-[10px] font-black uppercase tracking-tight text-slate-300 leading-tight">{t}</span>
                  </div>
               ))}
            </div>
         </div>
      </div>

      {idp ? (
        <div className="grid grid-cols-1 lg:grid-cols-12 gap-6 animate-slide-up">
           <div className="lg:col-span-5 space-y-6">
              <div className="p-6 bg-white rounded-[2rem] border border-orange-100 shadow-sm">
                 <div className="flex items-center gap-3 mb-4">
                    <div className="w-1.5 h-6 bg-orange-600 rounded-full"></div>
                    <h5 className="text-[11px] font-black text-slate-900 uppercase tracking-[0.2em]">Odak: {idp.focusArea}</h5>
                 </div>
                 <div className="space-y-2">
                    {(idp.identifiedGaps || []).map((gap: string, i: number) => (
                      <div key={i} className="flex gap-3 items-center p-3 bg-slate-50 rounded-xl border border-slate-100">
                         <div className="w-2 h-2 rounded-full bg-rose-500 shrink-0"></div>
                         <p className="text-[10px] font-bold text-slate-700 uppercase tracking-tight leading-tight">{gap}</p>
                      </div>
                    ))}
                 </div>
              </div>

              <div className="p-6 bg-slate-950 rounded-[2rem] text-white shadow-lg">
                 <h5 className="text-[9px] font-black text-orange-500 uppercase tracking-widest mb-4">AKADEMİK YOL HARİTASI</h5>
                 <div className="space-y-6">
                    <div className="border-l border-white/10 pl-4 relative">
                       <span className="text-[8px] font-black text-slate-500 uppercase block mb-1">3 AY: STABİLİZASYON</span>
                       <p className="text-[11px] font-bold text-slate-200 italic leading-relaxed uppercase">"{idp.roadmap.shortTerm}"</p>
                    </div>
                    <div className="border-l border-white/10 pl-4 relative">
                       <span className="text-[8px] font-black text-slate-500 uppercase block mb-1">12 AY: UZMANLIK</span>
                       <p className="text-[11px] font-bold text-slate-200 italic leading-relaxed uppercase">"{idp.roadmap.longTerm}"</p>
                    </div>
                 </div>
              </div>
           </div>

           <div className="lg:col-span-7">
              {idp.autoGeneratedPresentation && idp.autoGeneratedPresentation.length > 0 ? (
                 <div className="bg-white rounded-[2rem] border border-slate-200 shadow-sm overflow-hidden h-full flex flex-col min-h-[400px]">
                    <SlideContent 
                      slide={idp.autoGeneratedPresentation[activeSlide]} 
                      index={activeSlide} 
                      total={idp.autoGeneratedPresentation.length} 
                      onPrev={() => setActiveSlide(s => Math.max(0, s - 1))}
                      onNext={() => setActiveSlide(s => Math.min(idp.autoGeneratedPresentation.length - 1, s + 1))}
                    />
                 </div>
              ) : (
                <div className="h-full flex flex-col items-center justify-center border-2 border-dashed border-slate-200 rounded-[2rem] opacity-30 text-center p-10">
                   <h3 className="text-xl font-black text-slate-400 uppercase tracking-[0.4em]">Müfredat Hazırlanıyor...</h3>
                </div>
              )}
           </div>
        </div>
      ) : (
        <div className="py-20 bg-slate-50 rounded-[2rem] border-2 border-dashed border-slate-200 text-center flex flex-col items-center justify-center">
           <button onClick={handleGenerateIDP} className="px-8 py-4 bg-slate-900 text-white rounded-2xl font-black uppercase text-[10px] tracking-widest hover:bg-orange-600 transition-all shadow-lg">GELİŞİM ANALİZİNİ TETİKLE</button>
        </div>
      )}
    </div>
  );
};

const SlideContent = ({ slide, index, total, full = false, onClose, onPrev, onNext }: any) => {
  if (!slide) return null;

  return (
    <div className={`flex flex-col justify-between h-full transition-all duration-700 ${full ? 'p-16 bg-slate-950 text-white' : 'p-8 bg-white'}`}>
      <div className="space-y-6">
        <div className="flex justify-between items-center relative z-[1001]">
           <span className={`text-[9px] font-black uppercase tracking-[0.4em] ${full ? 'text-orange-500' : 'text-orange-600'}`}>MODÜL {index + 1} / {total}</span>
           <div className="flex gap-4">
              {full && <button onClick={onClose} className="p-3 bg-white/5 hover:bg-rose-600 rounded-full transition-all text-white"><svg className="w-6 h-6" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={3}><path d="M6 18L18 6M6 6l12 12" /></svg></button>}
           </div>
        </div>
        
        <div className="space-y-4 relative z-10">
          <h4 className={`font-black uppercase tracking-tighter italic leading-[0.9] ${full ? 'text-7xl' : 'text-3xl text-slate-900'}`}>"{slide.title}"</h4>
          {slide.subtitle && (
            <p className={`font-bold italic leading-relaxed opacity-90 ${full ? 'text-2xl text-slate-400' : 'text-sm text-slate-500'}`}>"{slide.subtitle}"</p>
          )}
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-8 mt-8 relative z-10">
           <div className="space-y-4">
              <div className="space-y-2">
                {(slide.content || []).map((point: string, i: number) => (
                  <div key={i} className={`flex gap-3 items-center p-3 rounded-xl border transition-all ${full ? 'bg-white/5 border-white/10' : 'bg-slate-50 border-slate-100'}`}>
                     <div className="w-2 h-2 rounded-full bg-orange-600"></div>
                     <p className={`font-bold uppercase tracking-tight ${full ? 'text-sm text-slate-300' : 'text-[10px] text-slate-800'}`}>{point}</p>
                  </div>
                ))}
              </div>
           </div>
           {slide.visualPrompt && (
             <div className={`p-6 rounded-3xl border flex flex-col justify-center relative overflow-hidden ${full ? 'bg-orange-600/10 border-orange-500/20' : 'bg-orange-50 border-orange-100'}`}>
                <span className="text-[9px] font-black text-orange-500 uppercase tracking-widest block mb-2">KLİNİK PROJEKSİYON</span>
                <p className={`font-bold italic leading-relaxed ${full ? 'text-lg text-orange-100' : 'text-xs text-orange-950'}`}>{slide.visualPrompt}</p>
             </div>
           )}
        </div>
      </div>

      <div className={`mt-10 flex justify-between items-center pt-6 border-t ${full ? 'border-white/10' : 'border-slate-100'} relative z-[1001]`}>
        <div className="flex gap-4">
           <button disabled={index === 0} onClick={onPrev} className={`p-3 rounded-full transition-all border-2 ${full ? 'bg-white/5 border-white/10 text-white hover:bg-orange-600' : 'bg-slate-900 border-slate-900 text-white hover:bg-orange-600'} disabled:opacity-20`}>
              <svg className="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={3}><path d="M15 19l-7-7 7-7" /></svg>
           </button>
           <button disabled={index === total - 1} onClick={onNext} className={`p-3 rounded-full transition-all border-2 ${full ? 'bg-white/5 border-white/10 text-white hover:bg-orange-600' : 'bg-slate-900 border-slate-900 text-white hover:bg-orange-600'} disabled:opacity-20`}>
              <svg className="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={3}><path d="M9 5l7 7-7 7" /></svg>
           </button>
        </div>
        {slide.interactiveElement && (
          <div className="text-right max-w-md">
             <p className="text-[9px] font-black text-slate-500 uppercase tracking-[0.2em] mb-1">SORU & TARTIŞMA</p>
             <p className={`font-black uppercase italic tracking-tighter ${full ? 'text-xl text-orange-500' : 'text-sm text-orange-600'}`}>"{slide.interactiveElement.question}"</p>
          </div>
        )}
      </div>
    </div>
  );
};

export default StaffProfileView;
